// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
export const top100Films = [
    { displayName: "The Shawshank Redemption", value: 1994 },
    { displayName: "The Godfather", value: 1972 },
    { displayName: "The Godfather: Part II", value: 1974 },
    { displayName: "The Dark Knight", value: 2008 },
    { displayName: "12 Angry Men", value: 1957 },
    { displayName: "Schindler's List", value: 1993 },
    { displayName: "Pulp Fiction", value: 1994 },
    {
        displayName: "The Lord of the Rings: The Return of the King",
        value: 2003,
    },
    { displayName: "The Good, the Bad and the Ugly", value: 1966 },
    { displayName: "Fight Club", value: 1999 },
    {
        displayName: "The Lord of the Rings: The Fellowship of the Ring",
        value: 2001,
    },
    {
        displayName: "Star Wars: Episode V - The Empire Strikes Back",
        value: 1980,
    },
    { displayName: "Forrest Gump", value: 1994 },
    { displayName: "Inception", value: 2010 },
    {
        displayName: "The Lord of the Rings: The Two Towers",
        value: 2002,
    },
    { displayName: "One Flew Over the Cuckoo's Nest", value: 1975 },
    { displayName: "Goodfellas", value: 1990 },
    { displayName: "The Matrix", value: 1999 },
    { displayName: "Seven Samurai", value: 1954 },
    {
        displayName: "Star Wars: Episode IV - A New Hope",
        value: 1977,
    },
    { displayName: "City of God", value: 2002 },
    { displayName: "Se7en", value: 1995 },
    { displayName: "The Silence of the Lambs", value: 1991 },
    { displayName: "It's a Wonderful Life", value: 1946 },
    { displayName: "Life Is Beautiful", value: 1997 },
    { displayName: "The Usual Suspects", value: 1995 },
    { displayName: "Léon: The Professional", value: 1994 },
    { displayName: "Spirited Away", value: 2001 },
    { displayName: "Saving Private Ryan", value: 1998 },
    { displayName: "Once Upon a Time in the West", value: 1968 },
    { displayName: "American History X", value: 1998 },
    { displayName: "Interstellar", value: 2014 },
    { displayName: "Casablanca", value: 1942 },
    { displayName: "City Lights", value: 1931 },
    { displayName: "Psycho", value: 1960 },
    { displayName: "The Green Mile", value: 1999 },
    { displayName: "The Intouchables", value: 2011 },
    { displayName: "Modern Times", value: 1936 },
    { displayName: "Raiders of the Lost Ark", value: 1981 },
    { displayName: "Rear Window", value: 1954 },
    { displayName: "The Pianist", value: 2002 },
    { displayName: "The Departed", value: 2006 },
    { displayName: "Terminator 2: Judgment Day", value: 1991 },
    { displayName: "Back to the Future", value: 1985 },
    { displayName: "Whiplash", value: 2014 },
    { displayName: "Gladiator", value: 2000 },
    { displayName: "Memento", value: 2000 },
    { displayName: "The Prestige", value: 2006 },
    { displayName: "The Lion King", value: 1994 },
    { displayName: "Apocalypse Now", value: 1979 },
    { displayName: "Alien", value: 1979 },
    { displayName: "Sunset Boulevard", value: 1950 },
    {
        displayName:
            "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
        value: 1964,
    },
    { displayName: "The Great Dictator", value: 1940 },
    { displayName: "Cinema Paradiso", value: 1988 },
    { displayName: "The Lives of Others", value: 2006 },
    { displayName: "Grave of the Fireflies", value: 1988 },
    { displayName: "Paths of Glory", value: 1957 },
    { displayName: "Django Unchained", value: 2012 },
    { displayName: "The Shining", value: 1980 },
    { displayName: "WALL·E", value: 2008 },
    { displayName: "American Beauty", value: 1999 },
    { displayName: "The Dark Knight Rises", value: 2012 },
    { displayName: "Princess Mononoke", value: 1997 },
    { displayName: "Aliens", value: 1986 },
    { displayName: "Oldboy", value: 2003 },
    { displayName: "Once Upon a Time in America", value: 1984 },
    { displayName: "Witness for the Prosecution", value: 1957 },
    { displayName: "Das Boot", value: 1981 },
    { displayName: "Citizen Kane", value: 1941 },
    { displayName: "North by Northwest", value: 1959 },
    { displayName: "Vertigo", value: 1958 },
    {
        displayName: "Star Wars: Episode VI - Return of the Jedi",
        value: 1983,
    },
    { displayName: "Reservoir Dogs", value: 1992 },
    { displayName: "Braveheart", value: 1995 },
    { displayName: "M", value: 1931 },
    { displayName: "Requiem for a Dream", value: 2000 },
    { displayName: "Amélie", value: 2001 },
    { displayName: "A Clockwork Orange", value: 1971 },
    { displayName: "Like Stars on Earth", value: 2007 },
    { displayName: "Taxi Driver", value: 1976 },
    { displayName: "Lawrence of Arabia", value: 1962 },
    { displayName: "Double Indemnity", value: 1944 },
    {
        displayName: "Eternal Sunshine of the Spotless Mind",
        value: 2004,
    },
    { displayName: "Amadeus", value: 1984 },
    { displayName: "To Kill a Mockingbird", value: 1962 },
    { displayName: "Toy Story 3", value: 2010 },
    { displayName: "Logan", value: 2017 },
    { displayName: "Full Metal Jacket", value: 1987 },
    { displayName: "Dangal", value: 2016 },
    { displayName: "The Sting", value: 1973 },
    { displayName: "2001: A Space Odyssey", value: 1968 },
    { displayName: "Singin' in the Rain", value: 1952 },
    { displayName: "Toy Story", value: 1995 },
    { displayName: "Bicycle Thieves", value: 1948 },
    { displayName: "The Kid", value: 1921 },
    { displayName: "Inglourious Basterds", value: 2009 },
    { displayName: "Snatch", value: 2000 },
    { displayName: "3 Idiots", value: 2009 },
    { displayName: "Monty Python and the Holy Grail", value: 1975 },
];
