import AutoComplete from "@/components/AutoComplete";
import { top100Films } from "@/constants/global";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <AutoComplete list={top100Films} placeHolder="Movie" />
            </main>
        </>
    );
}
